version: "3.3"

services:
    wechat:
        image: "miaowoo/wechat:latest"
        restart: unless-stopped
        container_name: "wechat"
        environment:
            WC_AUTO_RESTART: "yes"
        ports:
            - "8080:8080"
            - "19088:19088"
        volumes:
            - "/home/wechat/files/:/home/app/WeChat Files/"
            - "/home/wechat/Applcation Data/:/home/app/.wine/drive_c/users/user/Application Data/"
            - "/home/external:/home/app/external"
        tty: true